### ISSUE TITLE
Config Database

### ISSUE THREAD

**Issue by Annika-Rosenvinge** [Annika-Rosenvinge/FlowOneBank#4]

**Comment by Annika-Rosenvinge** [comment]
- Cus Id
- Name
- ect

**Comment by Annika-Rosenvinge** [comment]
Der er lavet 2 tables en for customer og en for account, de er ikke sat sammen endnu

**Comment by Annika-Rosenvinge** [comment]
https://drive.google.com/file/d/18RUBMmiK68ckZLQoMNNLXp8hCRngyvWz/view?usp=sharing

**Comment by cobra-7777** [comment]
CREATE TABLE TransactionHistory (
	CusNumber int not null auto_increment primary key,
	CusName varchar (255) not null,
        TransactionHis varchar (255) not null
);

Table for storing transaction histories

**Comment by cobra-7777** [comment]
[Dump20210216.zip](https://github.com/Annika-Rosenvinge/FlowOneBank/files/5988348/Dump20210216.zip)

**Comment by Annika-Rosenvinge** [comment]
Den skal hedde for kunder
cusID int not null auto_increment primary key
cusName varchar (255) not null
phone int not null
